### ISSUE TITLE
king can be captured issue

### ISSUE THREAD

**Issue by MaciejGrzybacz** [MaciejGrzybacz/ChessGame#9]
You can capture black king, likely solution: check if position is correctly calculated 
![image](https://github.com/MaciejGrzybacz/ChessGame/assets/128727060/832ca390-f15f-46fd-8304-af210abff757)

![image](https://github.com/MaciejGrzybacz/ChessGame/assets/128727060/604faf62-6293-4466-8a8b-2e82adeefa95)

**Comment by MarcinSerafin03** [comment]
same issues as before (solved)
